networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - dev

  # bot:
  #   build:
  #     context: bot
  #   networks:
  #     - dev

      